apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-beta-sa
  namespace: assessment
  # annotations:
  #   # For Workload Identity (Phase 2 integration)
  #   iam.gke.io/gcp-service-account: app-beta-sa@<YOUR_PROJECT_ID>.iam.gserviceaccount.com
