apiVersion: v1
kind: Service
metadata:
  name: app-alpha-svc
  namespace: assessment
  annotations:
    cloud.google.com/backend-config: '{"default": "alpha-backendconfig"}'
  labels:
    app: app-alpha
spec:
  selector:
    app: app-alpha
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: ClusterIP    # Internal only; Ingress handles external access
